### ISSUE TITLE
Use common framing

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#101]
We have several types of top-level objects right now:

* UserInitKey messages
* Welcome messages
* Handshake messages
* Application messages

We should have a common framing layer that describes the object type (and optionally provides encryption), to prevent confusion among these types.  This would be analogous to the [TLS record layer](https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#rfc.section.5.1)

**Comment by katrielalex** [comment]
(cc @alexsherkin when they accept the invite :) )

**Comment by bifurcation** [comment]
Discussion with @beurdouche and @raphaelrobert 
* Some desire for privacy of header fields
  * Encrypt using a group key?
  * MAC (for low-entropy values like `sender`, `generation`)
  * Not doing this for -04, but note an OPEN ISSUE to discuss in Prague
* Likewise, concerns about using application keys for Handshake messages -> OPEN ISSUE
* @beurdouche will try to mature #131 in the next few days, otherwise we can do #120

**Comment by bifurcation** [comment]
Fixed by #155
