### ISSUE TITLE
Simplify nonce generation

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#103]
Right now, nonces used to encrypt application messages are derived off the key schedule.  Since the keys are effectively single-use, this could probably be done more simply, e.g., by using the generation number as the nonce.

**Comment by ekr** [comment]
The rationale for random nonces is a time/space tradeoff with mass surveillance on 128-bit keyspaces. See:
https://tools.ietf.org/rfcmarkup?doc=8446#appendix-E.2
and
https://eprint.iacr.org/2016/564
