### ISSUE TITLE
Handshake message parsing is ambiguous in type-safe implementations

### ISSUE THREAD

**Issue by rozbb** [mlswg/mls-protocol#119]
At least 2 existing implementations of MLS have some sort of curve-specific DH public key type. This is to ensure type safety and reduce the likelihood of the programmer accidentally using one point value for a different curve. For me, this is
```
enum DhPoint {
    X25519([u8; 32]),
    P256([u8; 32]),
}
```
The issue I run into is that I cannot unambiguously deserialize `DHPublicKey`s into a `DHPoint`. Recall the definition `opaque DHPublicKey<1..2^16-1>`. The parse of an unmarked sequence of bytes is dependent on ambient state, namely the `CipherSuite` of the current session. Notably, the value of this `CipherSuite` is not repeated in any top-level messages. This means that a given `Handshake` message will have at least two correct interpretations unless context is specified. 

This is not a massive issue, but one could imagine a case where a participant receives a message from another participant who somehow disagrees on the current `CipherSuite`. The receiver will parse all the messages correctly, check the signatures, and throw an invalid signature error. If we were to mark the type of the `DHPublicKey`, though, the receiver would parse the values and check that they agree with the current `CipherSuite`. This check will fail, and it will throw a decoherence error, which is more appropriate and informative.

`DHPublicKey` is not the only data type for which this ambiguity occurs. I propose that we change at least some `opaque` datatypes to enums. Currently, the not-really-bytes opaque types are

* `DHPublicKey`
* `SignaturePublicKey`
* `ECIES::ciphertext`
* `UserInitKey::signature`
* `Handshake::signature`
* `ApplicationPlaintext::signature`
* `Application::encrypted_content`

My own implementation makes distinctions between different signature types, ECDSA pubkey types, and ECDH pubkey types. Encrypted content is treated as a binary blob.

**Comment by burdges** [comment]
I'd kinda expect a trait instead of an enum for this in Rust, just because cipher suite agility creates many complexities.  If it's only a compile time choice, or protocol version number, then differentiating MACs and/or hashes might provide the desired protections.  Apologies if I've failed to understand all the goals here.

**Comment by rozbb** [comment]
No, this is a good point. I've chosen in my implementation to treat DH algorithms as trait implementations, and `DhPoint`s as data. So I would have something like `X25519.diffie_hellman(my_scalar, others_point)`. The reason I've chosen this representation for DH public keys is because these types cannot be known at compile time. If they could be, then I would probably use associated types for the aforementioned trait impls. So I have enums which I unwrap at runtime, and panic if there's a type error then. It's not pretty, but it'll hopefully prevent some bad things from happening.

**Comment by burdges** [comment]
Oh?  I'm curious why the types cannot be known?  Is it for linking with C or something?

**Comment by rozbb** [comment]
Well the types of, say, the DH implementor is not known. If DH operations are implemented as a trait `DiffieHellman`, then there are structs called `X25519` and `P256`. So if these are marked by bytes, say 0x00 and 0x01, respectively, then what is the return type of `deserialize_dh_from_byte(marker: u8) -> ???`.
Well naturally it would be a `dyn DiffieHellman`. So say you do `let dh_impl = deserialize_dh_from_byte(b)`. Then what types does `dh_impl.multiply_basepoint(scalar: ???) -> ???` take and return? If each DH implementation has their own scalar type and point type, how can I know what to give this function?

**Comment by burdges** [comment]
I'd love it if Rust had type parameters for modules, but no such luck.  Instead, we often create parameters traits for the entire module or crate, commonly called `Trait` or `Params`.  It'd bloat the binary though if you need both X25519 and P256 in the same code, hence my C question.  Anyways not a big deal.  :)

**Comment by bifurcation** [comment]
From a protocol design POV, there are basically two options here:

1. Set the ciphersuite once, and force implementations to tell their deserializers what it is
2. Set the ciphersuite on every object, and force implementations to verify that all the  ciphersuites are consistent

IMO, option 1 is likely to be less error-prone, simply because it touches less code, and it is more likely to fail if you get it wrong.  It also doesn't seem *that* burdensome to implement.  Yes, you have to route the ciphersuite around to all the right places, but things like templates and generics can help a lot.

**Comment by beurdouche** [comment]
I agree with Richard, the preferable way is usually to do 1 : ) It is more a implementation specific state machine enforcement issue than a protocol issue so I will close this, but feel free to discuss more in the Implementation issues if you feel like it is necessary.

**Comment by rozbb** [comment]
Yeah, I tend to agree with this argument. I think I can find a way to pass state into my deserializer.
