### ISSUE TITLE
STROBE

### ISSUE THREAD

**Issue by burdges** [mlswg/mls-protocol#130]
There is a nifty advantage of using Mike Hamburg's STROBE for symmetric cryptography:  
 
Applications using WASM virtual machines should improve performance by using native code for cryptography.  STROBE works well for this because all actual processing is handled by *one* call that processes an arbitrary amount of data.  You always require multiple STROBE calls per operation in practice of course, but only O(1) cals.  If you wrapped say a ChaCha or Keccak permutation directly then you’d have O(data_size) calls.  In short, STROBE simplifies the WASM call boundary dramatically without much performance penalty. 

In MLS, you might favor adding ChaCha into your WASM call boundary anyways because STROBE lacks any round count configuration.  I wanted to mention this however since messengers do commonly get implemented in VMs.

**Comment by beurdouche** [comment]
Hi Jeff, I don't think this is much of an issue for our use cases, so I'll close the issue for now, but feel free to discuss this on the mailing list if you feel strongly about using STROBE as a base primitive ; )
