### ISSUE TITLE
Allow direct initialization

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#150]
We have a long-standing OPEN ISSUE on creating a group with a single Init message instead of  N Add messages, which would change the work of initialization from O(N log N) to O(N).  I would propose roughly the following:

```
struct {
    Welcome creator_info<0..2^32-1>; // Welcome from one-member group to each joiner
    UserInitKey members<0..2^32-1>; // Info to populate at the leaves
    DirectPath creator_update; // Update from the creator to warm the tree
} Init;
```

Then the processing would be:

* Find the welcome that's for you
* Initialize a one-member tree from the Welcome
* Use the UserInitKeys to populate the leaves of the tree
* Use the DirectPath to populate the creator's direct path (as in Update)

**Comment by beurdouche** [comment]
Fixed by https://github.com/mlswg/mls-protocol/pull/171
