### ISSUE TITLE
? Include the node_hash in the RatchetNode struct

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-protocol#161]

**Comment by beurdouche** [comment]
@bifurcation I am not immediately clear if we need that or not. I think we do not have to send it in certain cases like update, but I think a receiver of an Add cannot recompute it, right ? We do send it in the formal spec...

**Comment by bifurcation** [comment]
I don't think we need this.  Right now, we presume that each member caches the whole tree, which means that they can compute all the node hashes.  If we want to enable members to exist with log state, then we'll need to add a bunch of node hashes to the protocol messages.
