### ISSUE TITLE
Clarify obligation of clients to Update

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-protocol#168]
It has been noted that we don't discuss enough he influence of clients refusing to update in this document. The architecture document briefly explain why we minimally should evict clients that refuse to update to preserve FS or PCS. I think we actually enforce a MUST and provide a minimal recommendation. 
```
### Membership and offline members
Because Forward Secrecy (FS) and Post-Compromise Security (PCS)
rely on the deletion and replacement of keying material,
any client which is persistently offline
may still be holding old keying material and thus be a threat
to both FS and PCS if it is later compromised.
MLS does not inherently defend against this problem, but
MLS-using systems can enforce some mechanism for doing
so. Typically this will consist of evicting clients which
are idle for too long, thus containing the threat of
compromise. The precise details of such mechanisms are
a matter of local policy and beyond the scope of this document.
```

**Comment by bifurcation** [comment]
The Security Considerations correctly notes that that you only get PCS when you update, which I think is sufficient for this document.  If we want to lay out operational recommendations for how Updates should be arranged in practice, that seems like a better topic for the architecture document, or for implementation considerations (cc @kkohbrok).
