### ISSUE TITLE
Include message type in AAD when encrypting to public keys in leaves of ratchet tree

### ISSUE THREAD

**Issue by Bren2010** [mlswg/mls-protocol#214]
The protocol currently uses the public keys in the leaves of the ratchet tree for two purposes: For encrypting path secrets, and for encrypting WelcomeInfo data. We should include the type of message we're sending in the HPKE AAD for that message.

Taking messages meant for one purpose and using them for another might leak information about the plaintext because decryption will succeed but not subsequent processing. Ex: Putting a ciphertext containing a path secret in a Welcome message and observing error "unknown group id: abcdef123..." or similar

**Comment by bifurcation** [comment]
Question: Should this be HPKE `info` or `aad`?
