### ISSUE TITLE
Restrict life of ClientInitKey

### ISSUE THREAD

**Issue by Bren2010** [mlswg/mls-protocol#215]
Generally, the protocol provides no way to prevent ClientInitKeys from being re-used.

One case where this matters: If a user's ClientInitKey is compromised, the DS can serve it to anybody that wants to communicate with the user and immediately decrypt the user's communication, for the rest of their identity key's life.

We could put an expiry on ClientInitKeys to limit their effective lifespan. Or something else?

**Comment by bifurcation** [comment]
As discussed in the interim meeting (and in #225), the general goal here is to limit inappropriate replay of CIKs by CIK servers.  This can be done either in the CIK itself or by expiring/revoking the credential used to sign the CIK.

**Comment by bifurcation** [comment]
Fixed in #234
