### ISSUE TITLE
Address risk of re-using nonces after state loss

### ISSUE THREAD

**Issue by Bren2010** [mlswg/mls-protocol#216]
Nonces and keys are generated deterministically. If a client's state is rolled back to a previous version (because the process crashed, for instance), then the client is very likely to re-use the same key+nonce pair to encrypt a different application message. This breaks the confidentiality of the AEAD.

Consider using explicit nonces (even small ones will do) or SIV-like constructions.

**Comment by beurdouche** [comment]
Denis Jackson already discussed this, the WG, including I, was pretty conservative
at the time but I am feeling more and more we should do it, indeed…

There are other linked problems that I’ll discuss today but in general, in case of recoverable
state loss I would strongly favor mandating an update which would definitely help with
the problem. Detecting such losses is probably not trivial though :) 

B.

**Comment by beurdouche** [comment]
@bifurcation Notes for reference:The other solution we thought about was using the fresh explicit nonce as a re-randomizing solution for the deterministic handshake nonce.
