### ISSUE TITLE
Signatures in MLSPlaintext should cover entire group context

### ISSUE THREAD

**Issue by Bren2010** [mlswg/mls-protocol#217]
Signatures that go in the MLSPlaintext field right now only include the group ID and epoch. The group ID does help bind the message to a specific group, but group IDs are arbitrary and it seems multiple groups could have the same ID.

We should include the whole group context object in the data that's signed, to prevent messages from being copied from one conversation and pasted into another conversation with the same group ID.

**Comment by beurdouche** [comment]
Yes, the lack of context has been pointed out by Karthik and I at the last interim.
I said I would fix this but I didn’t find time to write the PR yet, I’ll try to do that today.

Thanks for the remainder...
