### ISSUE TITLE
Expose extended group attributes to new/existing members

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#227]
It could be useful for groups to agree on extended attributes (@psyoptix to provide examples), which are provided to new members and agreed by existing members.  Syntactically, this would mean:

* An extensions field in the WelcomeInfo message
* Including that field in the GroupContext so that it is confirmed that all members agree

That is, these attributes should follow the same general pattern as ciphersuites and versions, where the CIK advertises them (cf. #224) and the group picks and confirms.

**Comment by beurdouche** [comment]
We now have CIK in the leaves #254, hence exposing not only the credential but also the extensions. We currently don't have mechanisms to extend group attribute within the protocol after initial "agreement" provided by accepting the message from the creator.
