### ISSUE TITLE
Should direct paths include the root?

### ISSUE THREAD

**Issue by kelrit** [mlswg/mls-protocol#258]
In the "Ratchet Trees" section it specifies that a direct path does not include the root. From an ad hoc discussion with @bifurcation in Singapore this may not be required. I at least don't see a reason for it - in  "Synchronizing Views of the Tree" it specifies to transmit information "for each node in the direct path of the leaf, as well as the root", and other mentions of direct paths seem to assume it includes the root.

**Comment by beurdouche** [comment]
The path secret for the parent of the root in not included but the path secret at the level of the root has to be encrypted to the non-updated child subgroup. Can you point us to a place where you think the draft is incorrect ? If there is one we can fix it... : ) Thanks.

**Comment by kelrit** [comment]
In particular the "Ratchet Trees" section that specifies that "[t]he direct path of a root is the empty list" looks incorrect. However the usage in the draft seems to imply it does include the root, or specifies "intermediate nodes and the root". It appears more natural to just include the root node (or I've seriously misunderstood something here).

Semi-appendix: all mentions of "Direct path":

**Synchronizing Views of the Tree** section:
> When a client proposes a change to the tree (e.g., to add or remove a member), it transmits a handshake message containing a set of public values for intermediate nodes in the direct path of a leaf.

This message contains the public key for the root node as well.

> To perform an update for a leaf, the sender broadcasts to the group the following information for each node in the direct path of the leaf, as well as the root

Uses direct path with the root.

> Compute the updated path secrets.
> - Identify a node in the direct path for which the local member is in the subtree of the non-updated child.

This node could be the root node.

> Merge the updated path secrets into the tree.
> - Replace the public keys for nodes on the direct path with the received public keys.

This could also be the root node.

**Direct paths** section:

> As described in {{ratchet-tree-updates}}, each MLS message needs to transmit node values along the direct path of a leaf. The path contains a public key for the leaf node, and a public key and encrypted secret value for intermediate nodes in the path. In both cases, the path is ordered from the leaf to the root; each node MUST be the parent of its predecessor.

This should also include the root node.

**Group Creation** section:

> The only choices the creator makes here are its own HPKE key and credential, the leaf secret from which the Commit is built, and the intermediate key pairs along the direct path to the root.

The creator also decides the root node key pair.

> Process the path value to update the ratchet tree referenced by the provisional GroupContext and generate the update secret:
> Update the ratchet tree by replacing nodes in the direct path of the sender with the corresponding nodes in the path (see {{direct-paths}}).

This replaces the root node secret as well.

**Welcoming New Members** section:

> In the same encrypted package, the committer transmits the path secret for the lowest node contained in the direct paths of both the committer and the new member. This allows the new member to compute private keys for nodes in its direct path that are being reset by the corresponding Commit.

> Identify the lowest node at which the direct paths from index and signer_index overlap. Set private keys for that node and its parents up to the root of the tree, using the path_secret from the KeyPackage and following the algorithm in {{ratchet-tree-updates}} to move up the tree.

This node could be the root node.

**Comment by beurdouche** [comment]
I believe this has been clarified as part as the redefinition of the DirectPath in the Leaf CIK PR
