### ISSUE TITLE
Redundant information in MLSPlaintextCommitContent

### ISSUE THREAD

**Issue by raphaelrobert** [mlswg/mls-protocol#272]
`MLSPlaintextCommitContent` contains all of the Proposals that were previously sent within the same epoch. This seems unnecessary, since all members should have them anyway. The list of `PorposalIDs` in the actual `Commit` message should be enough for members to parse and validate a `Commit` message.

We should discuss if we can de-duplicate this, since the list of Proposals might be quite long.

**Comment by bifurcation** [comment]
The current definition of `MLSPlaintextCommitContent` is as follows;

```
struct {
  opaque group_id<0..255>;
  uint64 epoch;
  Sender sender;
  ContentType content_type = commit;
  Commit commit;
} MLSPlaintextCommitContent;
```

Maybe this issue is obsolete?

**Comment by raphaelrobert** [comment]
Seems it is now obsolete indeed.
