### ISSUE TITLE
Add/Welcome message should send the epoch secret and not init+commit secrets

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-protocol#277]
Sending the `init_secret` and the `commit_secret` at once seem equivalent to sending the `epoch_secret` but I don't think it is actually the case since the message could be rejected by the DS, breaking the encryption key of that message would hence still have consequences even if the message is rejected.

Technically this is also breaking secrecy of the `init_secret` because the principals of the protocol which are associated to its secrecy are the members of the previous epoch, while the principals associated to the `epoch_secret` do contain the newcomer.

I think we should update this mechanism to send the `epoch_secret` directly. DIscuss...

**Comment by bifurcation** [comment]
Fixed in #247
