### ISSUE TITLE
Make Editor's Copy and WG draft compare work properly

### ISSUE THREAD

**Issue by seanturner** [mlswg/mls-protocol#289]
Please fix the link on the repo page to display diffs between the current editor's draft and the WG draft.  Now, it should PRs comparing back to the -00 version.

**Comment by beurdouche** [comment]
@katrielalex Any change you could have a look at this when you have some time ? : )

**Comment by katrielalex** [comment]
Yeah, I'm gonna fix the CI and I can take a look at this as well. I tried to get it done before the interim but, well, excuses excuses

**Comment by beurdouche** [comment]
Ahah... ;) No problem!!
Thanks !

**Comment by bifurcation** [comment]
@katrielalex -- last call on this, or i'm just going to close it

**Comment by katrielalex** [comment]
Sorry. As you will have guessed, this fell through the cracks. I'll try this week to fix it out and close it out if I don't get to it this weekend :/
