### ISSUE TITLE
Detection of tree forks by recipients via a commitment

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-protocol#291]

**Comment by kelrit** [comment]
There's a few implications of simply allowing forks:

- FS issues - clients would need to use init_secret twice, which means keeping around init_secret for a potential fork, which breaks FS. One resolution here is to use something from the ASTree for init_secret (maybe the nth app secret, or a new ratchet derived from astree_node_[n]_secret).
- Does detection yield any sort of meaningful resolution technique? Are we better off than we are now in terms of user experience? (What we have now, if the DS fails to order, is two (or N) groups of clients operating on different versions of the tree, which effectively partitions the group)

I wrote about this here: https://mailarchive.ietf.org/arch/msg/mls/A4mVaXT-rqwZTNYXrC1TDb6XC_o suggesting merges as a resolution technique. The main downside is clients would need to keep around the list of proposals for a while.
