### ISSUE TITLE
How to derive group_info_key from the init_secret

### ISSUE THREAD

**Issue by ericcornelissen** [mlswg/mls-protocol#293]
In the [latest version of the draft in the section _Commit_](https://github.com/mlswg/mls-protocol/blob/13a4e3c8b0ee3e8b0145fb7c5bd8d6261f4b8520/draft-ietf-mls-protocol.md#commit) there is a sub-bullet for creating the GroupInfo object/Welcome message that says:

> Encrypt the GroupInfo using the key and nonce derived from the `init_secret` for the current epoch (see {{welcoming-new-members}})

Then, in [the section _Welcoming New Members_](https://github.com/mlswg/mls-protocol/blob/13a4e3c8b0ee3e8b0145fb7c5bd8d6261f4b8520/draft-ietf-mls-protocol.md#welcoming-new-members) it is stated that:

> From the `init_secret` in the decrypted KeyPackage object, derive the `group_info_secret`, `group_info_key`, and `group_info_nonce`. Use the key and nonce to decrypt the `encrypted_group_info` field.

However, from what I can tell, it is not explained anywhere how the _key and nonce_ should be derived from the `init_secret`. If it is somewhere, can someone point it out to me? If it is not in the RFC, should it be included?

**Comment by beurdouche** [comment]
Thanks! There is indeed missing definitions in the document.

On a side note, I labelled this a security issue as I suspect there is a design issue to handle. The secrets derived from the init_secret are cryptographically associated to the previous group, not the current one, which breaks the secrecy invariant. I would much prefer to derive and encrypt under keys that are cryptographically associated to the new group and reveal those to the newcomer.

**Comment by beurdouche** [comment]
Relates to #277

**Comment by bifurcation** [comment]
I will make sure this gets covered in the revived #247

**Comment by bifurcation** [comment]
Fixed in #247
