### ISSUE TITLE
Order in which proposals should be applied is a little bit vague

### ISSUE THREAD

**Issue by ericcornelissen** [mlswg/mls-protocol#300]
The [Commit section](https://github.com/mlswg/mls-protocol/blob/d460925cac306275e529a6c657e74eed653cf11b/draft-ietf-mls-protocol.md#commit) writes:

> Generate a provisional GroupContext object by applying the proposals referenced in the initial Commit object in the order provided, as described in {{proposals}}. [...]

However, from this it is not immediately clear to me in which order the collections of proposals `updates`, `removes`, and `adds` are to be applied. I assume it should be in that order because it makes practical sense and because they're written in that order in the Commit struct.

If my guess is correct, perhaps it would be useful to make this explicit? E.g.:

 > Generate a provisional GroupContext object by applying the proposals referenced in the initial Commit object, as described in {{proposals}}. First the list of update proposals, then the list of remove proposals, and last the list of add proposals. [...]

**Comment by bifurcation** [comment]
@ericcornelissen - I agree with your interpretation here.  Could you make a PR with some proposed wording?

**Comment by ericcornelissen** [comment]
Apologies for closing/opening the issue. I will open a PR to update the wording.
