### ISSUE TITLE
Targeted message

### ISSUE THREAD

**Issue by raphaelrobert** [mlswg/mls-protocol#301]
It might be interesting to have a mechanism to send targeted messages within a group. The recipient could either be a leaf node or an intermediary node (in which case you send the message to a subgroup).
There certainly is a need for that kind of functionality in some messengers (think read receipts that shouldn't be broadcasted to the whole group, etc.).
A starting point could be:
 - KEM to the public leaf key and combine that with something from the key schedule for the first message
 - hash ratchet forward for subsequent messages within the same epoch (FS)
 - include the new freshness in the forward ratcheting after an epoch an change (does that mean we inherit PCS guarantees?)

Just a thought for now but worth pursuing IMHO.

**Comment by burdges** [comment]
In this vein, I think "cryptographic introductions" actually matter quite a lot, even when you make the participants start a seperate channel, so any authentication property you can extract here helps enormously.  I suppose TreeKEM lacks any semi-ephemeral public key for the parties lying around like in Axolotl or ART, right?

**Comment by raphaelrobert** [comment]
The leaf nodes contain ClientInitKeys which allow you to authenticate members through the AS. So KEMing to a leaf node is authenticated and KEMing to intermediary nodes would be authenticated in the sense that only the leaves from the subtree would know the private key of the intermediary nodes. That notion of authentication seems less strong, but tree signatures should give some additional confidence.

> I suppose TreeKEM lacks any semi-ephemeral public key for the parties lying around like in Axolotl or ART, right?

Do you mean something like prekeys? MLS has ClientInitKeys for that.

**Comment by raphaelrobert** [comment]
After some discussion with @beurdouche we realised this could be generalised to a more generic concept to send application messages.

The parameters would be:
 - Send from inside vs outside
 - Send to the whole vs send to subtree vs send to leaf node

**Comment by burdges** [comment]
> Do you mean something like prekeys? MLS has ClientInitKeys for that.

No.  I do not track this project closely enough but at first blush what you describe sounds fine.  In particular the ClientInitKeys comes bound into client's participation in the current session, not just from some untrusted external server somewhere. 

Axolotl has an ephemeral public key the client retains as part of the current session, which you can mutate for use in introductions.  I donno if you need to mutate ClientInitKeys for use here too.

**Comment by br-hale** [comment]
The coming PR for the key schedule change to allow ciphersuite upgrades also enables an option for group branching that may be a viable alternative for this. A group can use a PSK to upgrade, but it could also use it to re-initialize the group. In this vein, a PSK can be used to branch a group as well (enabling side conversations among nodes or subtrees that partially rely on the group state). 

This is not quite the same, but would be an option using much of the current protocol infrastructure.

Notably, such branching and side-messages that are linked to the group state do have potentially significant effects on PCS (by any of the ideas in this discussion and simply in general). While development of an option that could be enabled in the future would be good, the understanding of PCS security in various group structures is already tenuous at the moment. I would not recommend that we roll-out this as an option in the first protocol version. Cas, Konrad, and I started looking into PCS effects when side-chats among sub-trees were allowed (assuming the subtree is not treated as a separate group), and found the possible cross-effects of compromise between groups when this is enabled grew very quickly and unexpectedly.

**Comment by raphaelrobert** [comment]
Branching is a cool thing as such, but I think it's orthogonal to the idea of targeted messages.
This stems from the real-world need to send certain messages only to one recipient, while the contextual scope of that message is still a certain group (as mentioned delivery and read receipts fall in that category).
By real-world I mean that messengers already have the need to do exactly that and right now they would have to resort to solving this on the application layer. It's not the end of the world, but one of the goals of MLS was to reduce the amount of low-level crypto operations messengers should solve on the application layer.
The risk of doing the wrong thing is higher if messengers solve this individually (because there is typically no scrutiny from academia at that level).

**Comment by kkohbrok** [comment]
@raphaelrobert in your first post you say that you might want to send a message to a sub-group. That would be where branching comes in, as it gives you a nice way to send messages to a sub-group and at the same time profit from all the security guarantees we got in the original group. I think sending to an intermediate note might be a bit unpractical, because the subgroup you want to send a message to might or might not be gathered under one such node. 

Maybe you can elaborate a bit more on the use-case?

"Targeted message" seems to suggest that you might want to send a message to a _user_ rather than to a specific group member (where by user, I mean someone who might run multiple devices and thus be the entity behind more than one node in the group. Sorry if I got the official terminology wrong here). If that is the case, again, a proper sub-group might be the way to go. A quick-and-dirty way might be to just KEM to multiple leaf nodes, so that might also be an option (if there are not too many of them and targeted messages are an infrequent thing).

**Comment by bifurcation** [comment]
I agree that there's some potential utility here, but it seems far enough afield of the main goal here (group AKE) that I would be inclined to not address it in the main specification.
