### ISSUE TITLE
Fix context for new-member-initiated Add

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#323]
Right now, the signature on an MLSPlaintext includes the GroupContext for the group.  If we are going to allow Add proposals signed by the new member, then this will need to change, because the new member doesn't know the GroupContext.

My preference would be to simply remove the GroupContext from the plaintext.  The Group ID is already included, so copy/paste protection can be added that way.  The other elements of the GroupContext effectively overlap with the Epoch that is already signed.

**Comment by Bren2010** [comment]
Haven't thought about this too deeply, but having the full GroupContext in MLSPlaintextTBS means that we know all the members agree on the state of the ratchet tree, the transcript, the extensions. Removing it means we would no longer have agreement on those, right?

**Comment by bifurcation** [comment]
We won't have confirmation of agreement as a result of signature verification.  The question is whether that is necessary.   If the MLSPlaintext was decrypted from an MLSCiphertext, for example, then the successful decryption of the MLSCiphertext implies agreement on all those things.

I suppose you could also switch the signature input based on SenderType, but that seems messier.

**Comment by Bren2010** [comment]
I'm not so sure that decrypting an MLSCiphertext implies agreement, because the crypto is symmetric. A man-in-the-middle can re-encrypt but not re-sign.
