### ISSUE TITLE
Use the same index for hashing parent and leaf nodes

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#328]
Right now the LeafNodeHashInput struct uses the index of the node among the leaves, while the ParentNodeHashInput struct uses the index of the node among all nodes.  This means that, for example, the index value will be the same for the second leaf and its parent (`1` in both cases).

We should probably just use the node index in both cases.

**Comment by Bren2010** [comment]
https://github.com/mlswg/mls-protocol/pull/320 is a better solution
