### ISSUE TITLE
Ratcheting of External PSKs

### ISSUE THREAD

**Issue by br-hale** [mlswg/mls-protocol#346]
This issue is to start a discussion thread on the suggestion made by Chris Wood under PR #336. The suggestion is not directly related to #336, so is listed here for discussion (some discussion already appears there):

`chris-wood:
Are "external" PSKs fixed? Would it make sense for them to also include an epoch, to allow applications to roll them forward for some FS?`

Current considerations: 
1) Is this a use case worth addressing for MLS (i.e. taking in an external PSK and then maintaining it in sync to protocol ratcheting)?
2) If so, is it sufficiently critical to be part of the protocol, or sufficiently peripheral to be discussed in the architecture?

**Comment by bifurcation** [comment]
I don't think this is really an issue we need to address here.  We already allow a different PSK to be injected at every epoch change.  How exactly the app chooses which PSK to inject at which time is their business, not ours.
