### ISSUE TITLE
Update security considerations

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#365]
The not-protocol parts of the document, including security considerations and some of the operational considerations, are mostly untouched since the beginning of this work.  As we get the protocol firmed up, we should revisit these parts to make sure they're up to date and give an accurate reflection of the concerns around the protocol.

**Comment by ericcornelissen** [comment]
One particular thing related to this that I noticed is that in the [Confidentiality of the Group Secrets section](https://github.com/mlswg/mls-protocol/blob/c3db39266505e9d202158d642d65918d35870e77/draft-ietf-mls-protocol.md#confidentiality-of-the-group-secrets) the first sentence:

> Group secrets are derived from (i) previous group secrets, and (ii) the root key of a ratcheting tree. [...]

is outdated as (ii) can now also be an all-zero vector, namely if `path` is not required and not set (as introduced in  #331 if I'm not mistaken).

**Comment by bifurcation** [comment]
I did a review of the Security Considerations and didn't see anything that needs fixing before WGLC.  The point that @ericcornelissen raises appears to have been fixed in some other PR.
