### ISSUE TITLE
Remove remaning raw Hash or add hash function to ciphersuite

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#386]
In #364, we changed from using HKDF to using the KDF from HPKE, which I thought removed the need for the ciphersuite to specify a hash function. As a result, ciphersuites no longer needed to specify a hash.

However, the transcript computations still have a raw `Hash()` invocation, not a KDF invocation.  So we need to either:

1. Change the transcript hash computations to use the KDF, or
2. Clarify that ciphersuites still specify a hash function (as before)

**Comment by ericcornelissen** [comment]
What about the `Hash()` call in the [Exporters section](https://github.com/mlswg/mls-protocol/blob/d1d5f56a5d83781042d19c830497ab5aa104907f/draft-ietf-mls-protocol.md#exporters) and the "hashes" for [Tree Hashes](https://github.com/mlswg/mls-protocol/blob/d1d5f56a5d83781042d19c830497ab5aa104907f/draft-ietf-mls-protocol.md#tree-hashes)?
