### ISSUE TITLE
Is the path secret used as PRK when doing Kdf.Expand?

### ISSUE THREAD

**Issue by yihuang** [mlswg/mls-protocol#392]
When evolving the ratchet tree, we'll do:
```
path_secret[n] = ExpandWithLabel(path_secret[n-1],
                                   "path", "", KEM.Nsk)
```
Does the `path_secret[n-1]` used as the `PRK` directly?
```
   HKDF-Expand(PRK, info, L) -> OKM
```
If that's the case, does that mean ` KEM.Nsk` should be `>= Kdf.Nh`?

Or should we do an extract before the expand?

**Comment by Bren2010** [comment]
Yes, `path_secret[n-1]` is used as the PRK directly. Why does `Kdf.Nh` matter?

**Comment by yihuang** [comment]
Because in https://tools.ietf.org/html/rfc5869, there's:
```
   HKDF-Expand(PRK, info, L) -> OKM
...
   Inputs:
      PRK      a pseudorandom key of at least HashLen octets
               (usually, the output from the extract step)
```

And length of `path_secret` is `KEM.Nsk`, so `KEM.Nsk >= Kdf.Nh`? unless we do an extract before expand?

**Comment by Bren2010** [comment]
I believe the PRK is just used as an HMAC key in HKDF, so I don't think that's a hard requirement

**Comment by yihuang** [comment]
> I believe the PRK is just used as an HMAC key in HKDF, so I don't think that's a hard requirement

I'm not sure how hard the requirement is, the RFC seems to treat it as a `MUST`? And [implementation added checked on this](https://github.com/RustCrypto/KDFs/blob/master/hkdf/src/hkdf.rs#L128), so it'll cause program to panic.

**Comment by bifurcation** [comment]
@yihuang I think you're right here.  We should probably change `KEM.Nsk` to `KDF.Nh`.
