### ISSUE TITLE
Draft structure/Editorial Changes

### ISSUE THREAD

**Issue by franziskuskiefer** [mlswg/mls-protocol#409]
This issue accompanies the e-mail [1] pointing out editorial issues with the draft and suggesting improvements.

TL;DR: I don't think the draft currently is what is needed to implement MLS. It needs an editorial overhaul with a better structure.

[1] https://mailarchive.ietf.org/arch/msg/mls/ZOy80Yp5bRhoM8fsQMGVwmFFEzY/

**Comment by beurdouche** [comment]
If we want an implementation document, which is a legitimate ask, we should write an implementation document.

**Comment by franziskuskiefer** [comment]
What's the purpose of the document if not for implementation?
In order for this draft to become an RFC it needs implementations. I don't see a way this will happen with the draft as is.

**Comment by beurdouche** [comment]
Specifying a functional behavior and providing a guide for implementation are two very different things.

Re: what you suggested in your email: Internal representations of the tree, the way you number the indices, how you implement them or the fact that you store some hashes in the nodes are completely irrelevant to this document.
Also, there is nothing formal about this appendix. 

On the other hand the information you need from this document is how to perform **computations** : things such as providing the arguments to the node_encap/node_decap functions which are required to generate a correct payload and a standard way to serialize abstract structures... etc.

**Comment by franziskuskiefer** [comment]
> Specifying a functional behavior and providing a guide for implementation are two very different things.

Right, the document is doing neither right now.

**Comment by rohan-wire** [comment]
I have an alternative organization of the first sections:
* Add the one sentence definition of `node` before the last paragraph of `##Tree Computation Terminology`
* Swap `##Ratchet Tree Nodes` and `##Views of a Ratchet Tree`

This seems to all flow nicely with very few forward references.

A more radical rewrite might 
* Move `#Group Evolution` forward before `#Cryptographic Objects`
but I don't think that is necessary.

I do like Richard's proposal to split `## Group State`

**Comment by bifurcation** [comment]
I'm considering this fixed after the series of reorg PRs that @rohan-wire @Bren2010 and I just finished.  

#565 #566 #567 #568 #569 #570 #571
