### ISSUE TITLE
Welcome message delivery

### ISSUE THREAD

**Issue by franziskuskiefer** [mlswg/mls-protocol#410]
It is currently unclear how welcome messages are supposed to be delivered. They should be sent to the clients directly without sending them to the group. But welcome messages as described in `11.2.1. Welcoming New Members` have no information about recipients. Neither are they framed in a way that would allow delivery.
Either the `Welcome` message should get a recipient field, or it should get framed as an `MLSPlaintext` and sent to the group instead.

**Comment by Bren2010** [comment]
The encoded `Welcome` struct is what's sent to the new user. The exact method of delivery is up to the application, but you have the user's identity in their credential which should be enough

**Comment by franziskuskiefer** [comment]
If message delivery and franking is something that's supposed to be left to the implementation, it should be removed for `MLSPlaintext` and `MLSCiphertext` as well. In fact description of the delivery service should be dropped all together from the architecture doc as well then.
But I don't think that's what you want. What's currently missing is a way to deliver `Welcome` messages only. All other messages are fine as far as I can see.
So if message delivery is something that should be described, as it is for all other messages, it should be done for `Welcome` messages as well.

**Comment by Bren2010** [comment]
What you mean when you say there's no way to deliver Welcome messages? You just send the encoded struct to the new user.

**Comment by franziskuskiefer** [comment]
> You just send the encoded struct to the new user.

How is the new user identified and how is the message supposed to get there? There's no real definition of users.

**Comment by bifurcation** [comment]
You're correct that the Welcome message only needs to be sent to the new members, though of course there's no security impact if it is also broadcast to the group.

I would argue that this is a problem for the DS to solve, for example by having the Welcome sender specify the routing identifiers for the recipients of the Welcome.  There's no need for these identifiers to be at all tied to the rest of the protocol, so there's no need for them to go in MLS; they can just be part of whatever framing is used to send MLS messages.

All that said, this could be a good topic for an issue on the architecture doc.  Basically, we want the DS to provide the following services:

1. Routing of KeyPackages from (potential) joiners to group members who might add them
2. Unicast/multicast routing of Welcome back to joiner(s)
3. Multicast routing of Proposals/Commits to the group

**Comment by Bren2010** [comment]
> How is the new user identified and how is the message supposed to get there? There's no real definition of users.

We have the new member's KeyPackage which contains a Credential which contains their identity.
