### ISSUE TITLE
Track Expected Types of Deployments

### ISSUE THREAD

**Issue by Bren2010** [mlswg/mls-protocol#411]
This ticket is meant to collect all of the use-cases and types of deployments that we support, or types of deployments that we've chosen not to support. In the future, I'd like us to take some time to make a sorta taxonomy of deployments -- think through the architecture / protocol decisions you need to achieve each use-case, and the security properties you get.

I'll start with a few:

- **Centralized Deployment:** Optimally simple client-side implementation.
  - Authentication Service: Endpoint run by service provider. Either trusted to act correctly or built with transparency technology.
  - Delivery Service: Endpoint run by service provider. Ensures a linear ordering of Commits.
  - Proposals and Commits are left as plaintext.
  - *Properties:*
    - The DS knows of all groups and which members are in each group, as well as the value of the group's ratchet tree.
    - Since the DS ensures a linear ordering of Commits, members can process Commits in the naive way.
    - The DS must process messages and maintain a copy of the ratchet tree.
    - New members can get a copy of a group's ratchet tree from the DS, meaning Welcome messages can be smaller.
    - Members are aware of all the other members in each group.
- **Broadcast Channel Deployment:** Server-side implementation that doesn't require strong coordination.
  - Authentication Service: Endpoint run by service provider. Either trusted to act correctly or built with transparency technology.
  - Delivery Service: Broadcast channel that sends new messages to all group members indiscriminately, combined with a separate mechanism for KeyPackage distribution.
  - Proposals and Commits are encrypted.
  - *Properties:*
    - The DS can infer which groups exist and which members are in each group, but this isn't required for it to operate. It does not know the ratchet tree.
    - Members must use a consensus protocol to decide on which Commit to accept if multiple are sent at once. This may imply forking or reverting to a previous state.
    - Since the ratchet tree isn't stored centrally, Welcome messages must be larger to accommodate the serialized tree.
    - Members are aware of all the other members in each group.
- **Anonymous Deployment:** Attempts to hide the membership of each group but does not attempt to hide the number of groups / number of members in each group.
  - Authentication Service: Endpoint run by service provider. Either trusted to act correctly or built with transparency technology. Must be accessed anonymously.
  - Delivery Service: Oblivious to *both* who writes a message to a given group, and who read that message. An onion network could be used, as long as a new circuit is created for each message. Ensures a linear ordering of Commits.
  - Proposals and Commits are encrypted. No additional framing is used beyond what the onion network dictates.
  - *Properties:*
    - The DS knows of all groups and how many members are in each group. It does not know the ratchet tree or the identities of group members.
    - Since the DS ensures a linear ordering of Commits, members can process Commits in the naive way.
    - Since the ratchet tree isn't stored centrally, Welcome messages must be larger to accommodate the serialized tree.
    - Members are aware of all the other members in each group.

Some that I need to think more about:

- **Hidden-Membership Deployment:** Allows groups where group members are unable to determine the identity of other members. All communication is either from/to the group creator.
- **Deniable Deployment:** Avoids signing messages sent to a group with a binding private key.
- **Federated Deployment:** Allows the users of multiple cooperating AS and DS providers to inter-communicate.

**Comment by bifurcation** [comment]
This seems worth thinking about, but more in the context of the architecture document than the protocol.

**Comment by bifurcation** [comment]
Closing this as a protocol issue, feel free to re-file on the architecture.
