### ISSUE TITLE
External commit for resync used with PSK

### ISSUE THREAD

**Issue by br-hale** [mlswg/mls-protocol#443]
A good point was raised by Jonathon Hoyland during the MLS IETF 109 meeting regarding possible concerns in using external commits for resync, particularly in the case of Alice adding/removing herself. Richard noted that this is a feature in the case that Alice is no longer synchronized with the group and therefore can use an external commit to add herself back in, removing the previous version.
 
As opposed to any newcomer joining with an external commit, the case of Alice re-joining presents a potential security issue. Namely, as currently specified (in my reading of the draft), an existing group member, Bob, has no means to distinguish between the following cases:

1) Alice needs to resync and therefore performs an external commit and removes her prior version.
2) Alice’s signature keys are compromised (it is not necessary for the adversary to compromise any group state). The adversary performs an external commit in Alice’s name, and then removes her prior version and impersonates her to the group.
 
One might hope that Alice notices that she is removed and communicates this to the group members OOB, but it is also possible that that she assumes some other reason for the removal, is offline, or simply is not active enough to take action for a fairly long compromise window. Even if she tries to use an external commit to get back into the group and then removes the adversary-as-Alice, there is no means for other group members distinguish the real Alice from the adversary-as-Alice and the process could be circular (until new valid identity keys are issued).
 
While a newcomer is a fresh source to be trusted or not, Alice has been “healing” along with the group and the above option (2) allows the adversary to bypass all of that.
 
The source of the problem is that when Alice re-syncs, she is not providing any validation of being the same/previous identity, so it is easy for other group members to accept that nothing more than a resync has taken place. Thus, a fairly straightforward solution is to require PSK use in cases where an external commit is used for resync. By enabling a PSK derived from a previous epoch during which Alice was part of the group to be injected with the external commit, Alice provides some proof of prior group membership and we avoid the total reset.

This is not quite PCS in that the attacker is active following compromise, but it is a linked case. As such it is important that a conscious decision is made regarding this (either as a slight change before the feature-freeze in line with the other changes that the editors have proposed, or as a working group decision to close the issue as out-of-scope).

**Comment by raphaelrobert** [comment]
Just to think this with what has been discussed on the mailing list: #439 will give members a way to do the distinction mentioned above.

**Comment by bifurcation** [comment]
@raphaelrobert - I don't think that's actually the case; it would only allow the members a way to recognize that Alice is replacing herself.

I think the right answer here is what Britta suggests, plus a little: We should enumerate a few specific constraints on the proposals that can be carried inline in an external Commit:
* There MUST be an Add proposal for the signer
* There MUST be an ExternalInit proposal
* There MUST NOT be any Update proposals
* If a Remove proposal is present, then:
    * The identity of the removed node MUST be the same as the identity in the Add KeyPackage
    * There MUST be a PSK proposal of type `ReInit`, referencing an earlier epoch of this group

**Comment by bifurcation** [comment]
Coming back to this after a few weeks, I'm actually not sure this is a problem worth solving.  The attack scenario (2) exists whether or not a member can resync without proving prior membership.  As long as (a) the group allows external Commits, and (b) the group does not require a new appearance of an existing identity to present a PSK from an earlier epoch, then the attacker can still do the attack by first joining, and then removing the old Alice.  The only difference in the case where the external commit also does the resync is that the two happen together.

It also doesn't seem unreasonable to regard the ability to resync from loss of all state except the signature key as a feature, not a bug.  Of course, that position would entail accepting that compromise of signature keys would be sufficient to impersonate the user, but that doesn't seem all that surprising, at least to me.

So this seems like a question of group policy to me.  Either the group requires ReInit PSKs on resync (and you can't recover from all-but-signature-key state loss), or it doesn't (and signature keys are the last resort).

This can be documented in the Security Considerations, in a new PR.  As far as #481, I think it's probably still worth adding the precision, but I would change the PSK part to MAY if not remove it entirely.

**Comment by bifurcation** [comment]
There is also a practical issue with using PSKs to prove past membership, in that if there have been joins since Alice lost state, the new joiners won't have the PSK.  This is of course a general issue with the proof-of-past-membership PSK, but it is particularly salient here.
