### ISSUE TITLE
Motivate Ratchet Trees

### ISSUE THREAD

**Issue by yaronf** [mlswg/mls-protocol#447]
The top of Sec. 5 has exactly one sentence before diving into tree terminology. Please explain at a high level what is the motivation for this structure and maybe how it fits into the rest of the protocol.

**Comment by bifurcation** [comment]
@yaronf - I put my own spin on this in #513.  Let me know if that looks good to you!

**Comment by yaronf** [comment]
@bifurcation Absolutely. Thank you!
