### ISSUE TITLE
Clarify ParentHash verification

### ISSUE THREAD

**Issue by franziskuskiefer** [mlswg/mls-protocol#457]
The [parent hash verification](https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#verifying-parent-hashes) is currently not very well described. Depending on the reading it might also be wrong.
In particular, the condition `If R is a leaf node, the check fails`, if implemented as described makes it so that valid parent hashes are rejected. Take for example a simple tree with two leafs where the right leaf (node 2) sends a commit. In this case the other leaf will reject the parent hash because it fails when going down to the right leaf.

This might be a wrong interpretation of the described verification procedure but then the description needs updating.
I suggest to add a more formal description of the parent hash generation and verification (e.g. pseudocode) to reduce ambiguity.

**Comment by psyoptix** [comment]
I think that condition should read "If R is a blank leaf node, the check fails".

**Comment by bifurcation** [comment]
Agree with @psyoptix here; the [relevant code in MLSpp](https://github.com/cisco/mlspp/blob/main/src/treekem.cpp#L468) matches this interpretation.  So I think we just need to adjust that text.

**Comment by franziskuskiefer** [comment]
I agree, this was fixed in #460
