### ISSUE TITLE
Trim tree after removal

### ISSUE THREAD

**Issue by raphaelrobert** [mlswg/mls-protocol#459]
Over time we lost the rule that the ratchet tree should also be trimmed after members have been removed (where it really makes sense), not only when members are added.

**Comment by bifurcation** [comment]
@suhasHere posted #461 to address this issue

**Comment by bifurcation** [comment]
Fixed in #461  - https://github.com/mlswg/mls-protocol/blob/main/draft-ietf-mls-protocol.md#remove
