### ISSUE TITLE
`typed` struct definition

### ISSUE THREAD

**Issue by kkohbrok** [mlswg/mls-protocol#499]
In many places, we use a `typed` pattern of struct, where we have a type uint, followed by a `select` statement decides the type of the following field based on the preceding type uint. For example the `Credential` struct:
```
struct {
    CredentialType credential_type;
    select (Credential.credential_type) {
        case basic:
            BasicCredential;

        case x509:
            Certificate chain<1..2^32-1>;
    };
} Credential;
```
Other examples are `Content`/`ContentType`, `PSKType` in `PreSharedKey`, `Sender`/`SenderType` and `Proposal`/`ProposalType`.

In the context of [an attempt at creating a macro for this pattern](https://github.com/RustCrypto/formats/pull/125), @franziskuskiefer suggested that we actually define a generic struct for this similar to the `optional<T>` pattern.
```
struct {
    T type;
    select(typed<T>.type) {
        T.variant1: 
            Variant1 
    }
} typed<T>
```
It would translate, for example, as follows for `typed<CredentialType>` (although we could then probably rename the enum from `CredentialType` to `Credential`:
```
struct {
    CredentialType credential_type;
    select typed<CredentialType>.type {
        CredentialType.basic: 
            Basic
        ...
    }
} typed<CredentialType>
```
It doesn't quite match up to what's currently in the spec (`Basic` instead of `BasicCredential`), but this rather naive approach is meant more as a basis for discussion than as a complete proposal. Let me know what you think!

**Comment by kkohbrok** [comment]
We're already somewhat formally extending the TLS serialization format with the `option` type, so why not continue with this. I think it would be useful in the spec. It would be useful for implementers to have a guideline for their template magic. But it might also benefit others in the same way that we are benefiting from the TLS spec.

**Comment by bifurcation** [comment]
I'm not worried about perturbing the TLS serialization format.  I just don't think there's much savings to be had, given that you need to specify the mapping of enum values to types anyway.  ISTM the `variant` syntax I proposed above is about as compact/elegant as you could make it, so I would propose we either do that or just close this issue with no action.

**Comment by kkohbrok** [comment]
Sounds good to me. An alternative would be to put this in the implementation-considerations doc. It currently doesn't have any content, so this might be a good first contribution.

**Comment by franziskuskiefer** [comment]
I suggest to move this to the implementation-considerations doc.

**Comment by bifurcation** [comment]
OK, sounds like we have consensus to move to implementation considerations, so I'm closing this.  

@kkohbrok — It might be good to start up a repo for that document, so that we don't lose things like this.  The other topic that comes to mind is the array-based tree representation (cf. #507).
