### ISSUE TITLE
Ciphersuite Addition

### ISSUE THREAD

**Issue by br-hale** [mlswg/mls-protocol#503]
I suggest that we consider including a ciphersuite that enables AES256 GCM with SHA384 and that for signatures ECDSA with P-384 (and SHA-384) is also permitted. The NSA restricts commercial applications to certain algorithms for applications that are used in or in coordination with the U.S. federal government and, from a general availability perspective, adding this could expand protocol use potential.

**Comment by bifurcation** [comment]
I presume you're thinking of [Suite B](https://apps.nsa.gov/iaarchive/programs/iad-initiatives/cnsa-suite.cfm) here?  I realize that the table specifies P-384 and SHA-384; is it your understanding that it forbids using bigger curves/hashes?

**Comment by br-hale** [comment]
Both Suite B and alignment to the [Commercial Capability Packages](https://www.nsa.gov/Resources/Commercial-Solutions-for-Classified-Program/Capability-Packages/#data-at-rest). The other options currently in the spec, size accounted for, do not align to requirements.

**Comment by bifurcation** [comment]
You didn't answer my question about forbidding the use of bigger curves/hashes.  Would the cases you're interested in be covered by the AES-256 / SHA-512 / P-521 suite?
