### ISSUE TITLE
KeyPackage ID vs KeyPackage Identifier

### ISSUE THREAD

**Issue by franziskuskiefer** [mlswg/mls-protocol#504]
There's a KeyPackageID ( 7.1. Key Package IDs ) and a KeyPackage Identifiers ( 7.4. KeyPackage Identifiers ) right now.
This is pretty confusing and probably not necessary. 

As far as I can tell the only difference is that the KeyPackageID has to be unique within a group. If we add this restriction to the KeyPacakge Identifier, for example by adding the key package hash, we could get rid of the KeyPackageID and the confusion.

**Comment by bifurcation** [comment]
IMO there is a useful distinction here.  The KeyPackage identifier extension is application provided, and can contain something more / differently useful than just a hash.

In #510 I renamed KeyPackageID to KeyPackageRef, which should help?

**Comment by franziskuskiefer** [comment]
Fair enough. The `KeyPackageRef` description is certainly better than the `KeyPackageID` and avoids confusion.
