### ISSUE TITLE
Include `context` in `MLSPlaintextTBS` for sender_type `NewMember`

### ISSUE THREAD

**Issue by kkohbrok** [mlswg/mls-protocol#528]
From what I can see, there is no reason not to sign the context in the case of an external init. I'm not sure why it got taken out, but while implementing external inits, verification went through even when including the context.

**Comment by bifurcation** [comment]
As I commented in #526, it's not even clear that we need this context any more for members any more, given `membership_tag` for MLSPlaintext and the AEAD of MLSCiphertext.  So I would propose we just remove the context added to MLSPlaintextTBS altogether.

@beurdouche IIRC you were the one that proposed adding the context.  WDYT?

**Comment by bifurcation** [comment]
This was fixed in #526
