### ISSUE TITLE
Make credential succession checking the AS's job

### ISSUE THREAD

**Issue by kkohbrok** [mlswg/mls-protocol#576]
Right now it says in the Update proposal section: "Verify that the set of identities attested by the credential is acceptable to the application for the participant being updated."

Firstly, I think this is a matter of authentication and thus the AS' job and secondly, it's a validation step that should probably go into the `KeyPackage Validation` section.

**Comment by bifurcation** [comment]
Discussion on virtual interim:

* Depends on what the boundary of the AS is:
    * Checking credential is valid
    * Also checking (credential -> credential) transitions
* Moving this check to KP validation section would make it clearer
* @kkohbrok to make a PR

**Comment by bifurcation** [comment]
Fixed by #584
