### ISSUE TITLE
Uniqueness of PSK proposals within a commit

### ISSUE THREAD

**Issue by tomleavy** [mlswg/mls-protocol#578]
Should multiple PSK proposals within a commit be able to reference the same `PreSharedKeyID `? I feel like this should be covered in the same way we state multiple removals for the same `KeyPackageRef` should result in the committer choosing one. Wasn't sure if this was an oversight or on purpose. 

I can submit a PR to clarify if this is something that should be addressed

**Comment by bifurcation** [comment]
I agree, duplicates are an error.  Committer MUST NOT include duplicates; receiver MUST reject Commit with duplicates.

@tomleavy  - Please send a PR!
