### ISSUE TITLE
Replace labeled signing with signing wire format?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#589]
With #523, we now have a wire format for each signed thing.  Could we just use this instead of a string label to distinguish signatures?

**Comment by TWal** [comment]
Something I like about string-based signature labels instead of binary ones, is that if you stare at the hexdump of the signed data there is absolutely no ambiguity about what is signed, because the first bytes are e.g. "MLS 1.0 KeyPackageTBS".
In the binary-based signature labels, the argument is that the first two bytes are e.g. "0105" and it's much more cryptic in my eyes.

**Comment by bifurcation** [comment]
Unless we convert the whole protocol to JSON, you're going to have to deal with binary stuff :)

**Comment by bifurcation** [comment]
Discussion on virtual interim:

* What's important is to have a "magic string" that distinguishes this protocol from other protocols
* Need to distinguish between
    1. Different structures within MLS
    2. Different versions of MLS
    3. MLS vs. everything else
* E.g., "MLS 1.0 KeyPackageTBS" ~> protocol / version /  type
* In addition to already having it, having the protocol distinguisher in ASCII gives greater confidence
    * "Intra-protocol" identifiers can be small
    * "Inter-protocol" identifiers need to be larger to reduce collision probability
    * Consider introducing some standard prefix to "MLS"
* If we're going to have both ASCII distinguisher and `wire_format`, spec needs to enforce equivalence
    * Could also omit wire_format from signature and rely on ASCII distinguisher alone
    * TODO(@TWal) Check that this is clear in the spec, see if wire format should be omitted

**Comment by bifurcation** [comment]
When we discussed this on the virtual interim, I forgot about #590, which provides a protocol-internal version.  That gives us small distinguisher for the version, so we're down to the inter-protocol distinguisher.
