### ISSUE TITLE
Should `GroupInfoTBS` contain the protocol version?

### ISSUE THREAD

**Issue by stefunctional** [mlswg/mls-protocol#607]
[The section about adding members to a group](https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.html#name-adding-members-to-the-group) defines `GroupInfo` and ` GroupInfoTBS` and states the following:
> The signature covers the following structure, comprising all the fields in the GroupInfo above signature

All the fields above `signature` in `GroupInfo` includes `version`, but `version` is not in `GroupInfoTBS`. Should it be or should the wording about which fields are included be amended?

Thank you.

**Comment by bifurcation** [comment]
In #600, the `version` field was removed from `GroupInfo`, so I think this ambiguity has been resolved.  Note that the version is still authenticated via the version string in `SignWithLabel`.

**Comment by stefunctional** [comment]
Thank you.
