### ISSUE TITLE
Completely remove leaf_index (or keep it)

### ISSUE THREAD

**Issue by rohan-wire** [mlswg/mls-protocol#608]
Under the list of changes, one of these says that leaf_index is removed. However a search for index and indeces still shows several references to the leaf_index. These should be removed/replaced as well, or explain why we need Leaf Node Reference and leaf_index and when one gets used.

**Comment by TWal** [comment]
`leaf_index` was first removed in #487 in favor of node indices, and afterward re-introduced to remove node indices in #522.
Draft 12 was out between these two pull requests, I'm guessing the latter change will appear in the changelog of draft 13!

**Comment by bifurcation** [comment]
It looks to me like the following mentions of leaf index still exist:

1. The leaf node input to the tree hash
2. The ratchet tree serialization scheme (for the `ratchet_tree` extension)
3. The example code for array-based trees

Case (3) is optional, so I don't think it's an issue.  For case (2), removing the notion of indices would make it a lot harder to describe the serialization.  For case (1), removing the index would remove some of the rigidity of the tree hash (in particular, a blank subtree of the same size would have the same hash anywhere).

Overall, I'm not inclined to make this change.
