### ISSUE TITLE
Clarify order of operations in processing external join

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#648]
In #511, we removed the requirement for an external Commit to have an Add proposal, under the theory that the required `path` already has a leaf node for the new joiner.  When I went to implement this, however, I noticed some ambiguities. 

First, the Commit processing section doesn't mention when the new joiner is added.  The obvious approach is to do the add as part of the `path` processing, but that processing presumes that the sender is already in the tree (for example, there is no provision for extending the tree).

Second, the UpdatePath for an external commit needs to be done in a specific order in order to avoid a circular dependency.  The TreeKEM encapsulation done by the joiner uses the GroupContext a context parameter, including the hash of the tree being used.  But the LeafNode in the `path.leaf_node` has to have a parent hash in it, which can only be computed after the encapsulation operation.  This circularity can be resolved, but only by preparing the UpdatePath with the following specific steps:

1. Compute the path secrets
2. Compute the parent hash and the new leaf node
3. Compute the new tree hash
4. Encrypt the path secrets to the rest of the group

That rules out some implementations that compute path secrets and encrypt them in one traversal of the direct path (this is what MLSpp does now).

The options here are basically:

1. Re-add the Add proposal, thus having a throw-away temporary LeafNode for the joiner
2. Specify that the UpdatePath must be computed in the specific order above

To me, (2) seems like a pretty clear winner.

**Comment by bifurcation** [comment]
Actually, it seems like there's a simpler option here:

* Extend the definition of an ExternalInit proposal to say that part of how it is applied is to ensure there is a blank leaf in the tree, extending the tree if necessary.  (This implies that ExternalInit must be done after any Remove.)  The leftmost blank leaf is the sender's leaf for purposes of UpdatePath processing.
* The provisional tree used in encrypting path secrets is still the provisional tree, in the sense that all proposals have been applied.  This tree has a blank leaf for the UpdatePath sender.

If we clarify these points, I think everything else works unmodified.

**Comment by kkohbrok** [comment]
I agree with the first point. Even if the Add is not explicitly present, the external commit effectively emulates an Add anyway.

To the second point: The solution is only simpler if that's how you want to implement it 😜. I haven't tried it, but if you have chosen a different order of implementation, i.e. perform all changes to the provisional tree (including the update path and parent hash), then compute the tree hash and then encrypt the path, you now have to go and compute an additional tree hash before applying the update path, then apply the update path and keep the partial tree hash around for later encryption/decryption.

This was not a part of MLS that I have looked at from a provable security perspective, but I'm wondering what the consequences are from a security perspective if we're including a parent hash for an incomplete provisional tree.

**Comment by bifurcation** [comment]
It seems like the main question here is what tree is provided to TreeKEM encryptions of path secrets.  I'll call this the "context tree" below.

It sounds like you have in mind that the tree provided to TreeKEM has the UpdatePath applied as well as the proposals, but that's not what the spec says right now:

> "Provisional" refers to the ratchet tree and GroupContext constructed after applying the proposals that are referenced by the Commit. 

> "New" refers to the ratchet tree and GroupContext constructed after applying the proposals and the UpdatePath (if any).

> Create an UpdatePath using the provisional ratchet tree and GroupContext

The starting point for this issue is that the "provisional" tree right now doesn't really faithfully capture the tree you're encrypting to, at least in the sense that it has a different number of leaves.  That seemed wrong to me.

It seems like we have the following options here:

1. Do nothing. 
    * The context tree doesn't necessarily have a blank for the joiner.
    * Maximal divergence between the new tree and the context tree (among these options)
    * TreeKEM encryption operates on a different tree than the context tree

2. Ensure the provisional tree has a blank leaf for the joiner (as up-thread).
    * Context tree has a blank leaf for the joiner, but direct path doesn't match new tree
    * TreeKEM encryption can operate on the context tree, because the structure is correct

3. Use the "new" ratchet tree as the TreeKEM context.
    * Context tree is exactly the new tree -- could probably eliminate provisional
    * Requires separate steps for (1) updating tree nodes and (2) encrypting path secrets
    * ... when these are currently described together as effectively one operation

Personally, it seems like the answer is (2) or (3), and I probably lean toward (3).  I don't think (1) is insecure, because the context tree does capture all of the nodes to which path secrets are encrypted.  But the divergence is worrisome and it's cheap to do better.

Between (2) and (3), there's a trade-off between fidelity and spec change size.  The impact of (2) is more localized (just the ExternalInit section).  Updating the spec to do (3) will require amending the description of update paths as well as the Commit creation / processing rules (to separate update/encrypt and remove provisional, respectively).  But honestly, removing the provisional tree seems like a worthwhile simplification, so between that and the greater fidelity of the context tree, (3) seems worth the cost.

**Comment by bifurcation** [comment]
Actually, as I look into implementing this: We still need a provisional GroupContext, because the `confirmed_transcript_hash` will differ. But we can at least have two trees instead of three.
