### ISSUE TITLE
Tree hash and Parent hash definitions are confusing

### ISSUE THREAD

**Issue by rohan-wire** [mlswg/mls-protocol#655]
Regarding the Tree Hash
1. Including the parent_node in the tree hash which is supposed to be computed from the leaves, makes the definition appear circular to a new reader. Since the situation when you have blank nodes in the middle of a tree but not at the root is a rather complicated, the situation when you could calculate a tree hash using the parent_node is non-obvious.
2. In the description of Tree Hash the document says that the ParentNode object is optional "depending on whether the node is blank or not." This isn't clear specification language. Saying the parent_node object is present if the node is blank or present if the node is not blank would be clear. 
3. What if the parent node is also blank? What if the root is blank? 
4. I think an example with and without blank nodes would be appropriate.
5. Explaining the reason why the parent_node is included will help the reader establish a better mental model.

Regarding the Parent Hash
I still find this section super confusing. A few points
1. Using a tree hash (sibling_tree_hash) inside the parent hash is non-obvious. There should be some explanation about what property this is providing and that it is a tree hash and not a parent hash. (Honestly it was the third time I read the section that I realized that it was really the tree hash and not the parent hash of the sibling.) 
2. Using P, V, and S for Parent, target node, and sibling node is introduced here and never used anywhere else in the document. P for parent and S for sibling make sense. I can't tell what V is supposed to stand for, and it unfortunately could cause people to confuse the <V> vector notation used throughout, but shortly after introducing V for the target node. I propose using "N" for node or "X" instead.
3. There is one reference to the filtered direct path of U. Perhaps this is V, or a child of V?
4. The calculations are sufficiently complicated that I think this warrants a complete, non-trivial, worked example (possibly in an appendix). At some point we should consider providing test vectors in a future document, and this would be an ideal candidate.

**Comment by bifurcation** [comment]
Regarding the Tree Hash

> 1. Including the parent_node in the tree hash which is supposed to be computed
> from the leaves, makes the definition appear circular to a new reader. Since the
> situation when you have blank nodes in the middle of a tree but not at the root
> is a rather complicated, the situation when you could calculate a tree hash
> using the parent_node is non-obvious.

To be clear, the `parent_node` that is included in the tree hash is the node
whose subtree is being hashed.  The tree hash doesn't include only the leaves,
it includes all the nodes in the tree.

If you mean `parent_hash`, then yes, I agree the connection is a little subtle.
I've tried to explain this a little better.


> 2. In the description of Tree Hash the document says that the ParentNode object
> is optional "depending on whether the node is blank or not." This isn't clear
> specification language. Saying the parent_node object is present if the node is
> blank or present if the node is not blank would be clear.

Updated this to be clear that the ParentNode is omitted if and only if the node is blank.


> 3. What if the parent node is also blank? What if the root is blank?

Not clear what situation you mean here.  I think the specific computations are
pretty clearly specified for these cases.


> 4. I think an example with and without blank nodes would be appropriate.

Something like this was added in #689:

https://github.com/mlswg/mls-protocol/blob/main/draft-ietf-mls-protocol.md#verifying-parent-hashes

I extended the example and put it in an appendix.


> 5. Explaining the reason why the parent_node is included will help the reader
> establish a better mental model.

Assuming you mean `parent_hash` here, hopefully this is addressed by the above notes. 


> 1. Using a tree hash (sibling_tree_hash) inside the parent hash is non-obvious.
> There should be some explanation about what property this is providing and that
> it is a tree hash and not a parent hash. (Honestly it was the third time I read
> the section that I realized that it was really the tree hash and not the parent
> hash of the sibling.)

Added a note to clarify that this is the tree hash and why.


> 2. Using P, V, and S for Parent, target node, and sibling node is introduced
> here and never used anywhere else in the document. P for parent and S for
> sibling make sense. I can't tell what V is supposed to stand for, and it
> unfortunately could cause people to confuse the vector notation used throughout,
> but shortly after introducing V for the target node. I propose using "N" for
> node or "X" instead.

Changed to "D" for "direct path", and explained the semantics.


> 3. There is one reference to the filtered direct path of U. Perhaps this is V,
> or a child of V?

Actually it's the leaf, which is now called "L".


> 4. The calculations are sufficiently complicated that I think this warrants a
> complete, non-trivial, worked example (possibly in an appendix). At some point
> we should consider providing test vectors in a future document, and this would
> be an ideal candidate.

I think the example linked above does a pretty good job.  Feedback obviously
welcome.  Agreed that a test vectors document will be a useful follow-on.
