### ISSUE TITLE
Undefined behavior around removed Committer

### ISSUE THREAD

**Issue by Bren2010** [mlswg/mls-protocol#657]
It's not clear to me from reading the spec what should happen when a Commit includes a Remove proposal for the committer.

**Comment by rohan-wire** [comment]
I think that sending a Commit with a Remove Proposal for yourself (the sender of the Commit) doesn't make sense and should be invalid. If you want to remove yourself, it would be better to send a separate Remove Proposal. Then another member is obliged to Commit your Proposal. Of course if a all the members try to send a Proposal nearly simultaneously, the last member should probably Commit all the proposals before closing the group.

**Comment by bifurcation** [comment]
Yeah, I always thought it was illegal for a Commit to include a Remove for the Committer.  Flagging for @mulmarta as she's working on a proposal validation PR.

**Comment by kkohbrok** [comment]
Since the committer learns the secrets of the next epoch, committing a self-remove really should be illegal.
