### ISSUE TITLE
Specify that clients MUST ensure the group id is unique and fixed for each group.

### ISSUE THREAD

**Issue by Bren2010** [mlswg/mls-protocol#661]
Group ids are signed to bind certain information to specific groups. But I can imagine a case where a user mis-uses the group id to be something like a "room title" which lets an adversary control the group id and introduces potential problems.

- If we can prove that it's fine for a group id to be reused, then should we get rid of group ids?
- If not (as I expect), then group ids need to be guaranteed to be unique [globally | per client | per signing key] and we need to specify that.

**Comment by seanturner** [comment]
Discussed at 19 May interim. @Bren2010 to generate PR documenting fresh random value approach.

**Comment by Bren2010** [comment]
- Group IDs must be generated randomly by creator
- Clients and DS must check that group ids are unique as far as they know
