### ISSUE TITLE
More pictures

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#669]
* Add illustration of filtered direct path
* Add illustration of parent hash validation, including:
    * Leaves with no parent hash
    * Nodes with invalid parent hash
    * Skipping blank nodes
* Add corresponding derivations to Appendix A
* Move figure in Section 10.2 up to Section 10 as an overview

**Comment by bifurcation** [comment]
@Bren2010 Note that I have taken a stab at parts of this in #689 because it came along with some other tree stuff.

**Comment by Bren2010** [comment]
Duplicate #644
