### ISSUE TITLE
Define filtered direct path in Ratchet Tree Terminology

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#670]
Currently defined only briefly in "RatchetTree Evolution".  While that's where it's primarily used, it would fit better in the terminology section, especially if we expand it a little and add an illustration.

**Comment by Bren2010** [comment]
The problem here is that the definition of "filtered direct path" depends on the definition of "resolution" which isn't defined until a later section.

**Comment by bifurcation** [comment]
Indeed, so #689 proposes moving up the definition of resolution as well.
