### ISSUE TITLE
Minor section reordering

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#672]
* “Adding and Removing Leaves” after “Synchronizing Views of the Tree”
* Consider merging “Ratchet Tree Evolution” and “Synchronizing Views of the Tree” and “Update Paths”
* Swap “Joining via External Commits” and “Joining via Welcome Message”
* Restore section break for “Extensions”

**Comment by bifurcation** [comment]
Assuming people are OK with this, we should probably do it at a "pause" in PRs -- where we've merged a round and there are no new ones in flight -- in order to avoid merge conflicts.

**Comment by bifurcation** [comment]
If folks are OK with this, I will just implement it before shipping the new post-LC draft.

**Comment by rohan-wire** [comment]
> * Consider merging “Ratchet Tree Evolution” and “Synchronizing Views of the Tree” and “Update Paths”

I would skip this one. I've now interviewed 4 developers and one product manager who are reading the spec for the first time. I think it is a lot clearer divided up.
