### ISSUE TITLE
Discuss all the *ART deletion options

### ISSUE THREAD

**Issue by katrielalex** [mlswg/mls-protocol#7]
We talked about quite a number of different ways to do deletion in *ART groups. Give at least a high-level overview of the main ones, and mention their pros and cons. These include:

- just rebuild the tree
  - Pros: simple, easy, no extra operations
  - Cons: inefficient, puts the deleter in a trusted position in the group until _every_ remaining member has updated
- update deletee's key to blank
  - Pros: fairly simple, no extra operations
  - Cons: puts the deleter in a trusted position until the sibling or cousin of the deletee has updated
- send a delete secret over pairwise channels
  - Pros: no trusted positions
  - Cons: O(N), leaves a potentially-compromised leaf node in the tree
- send a delete secret by KEMing to everyone else
  - Pros: no trusted positions, efficient
  - Cons: leaves a potentially-compromised leaf node in the tree, multiple deletes interact in a complex way

**Comment by bifurcation** [comment]
@katrielalex I think the algorithm in #59 is explicitly double-joined.  When I get time, I'll file another PR to move to the delete-without-double-join algorithm I posted to the list (i.e., puncture the tree).

**Comment by bifurcation** [comment]
Since we're no longer using ART, I think this issue is no longer relevant.
