### ISSUE TITLE
Document compilation drop accents

### ISSUE THREAD

**Issue by TWal** [mlswg/mls-protocol#719]
Hello,

In the ["contributors" section](https://github.com/mlswg/mls-protocol/blob/main/draft-ietf-mls-protocol.md?plain=1#L5101), my name is correctly written with the "é" accent, however when it is compiled, the accent is dropped, e.g. [here](https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.html#section-18-1.14) or [here](https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.txt).

It looks like this letter is the only non-ascii character in the whole document, is this the expected behavior when compiling an RFC, or is it an issue in [martinthomson/i-d-template](https://github.com/martinthomson/i-d-template) that I should track?

Thanks!

**Comment by bifurcation** [comment]
This is a tooling issue.  Currently, the only way to include non-ASCII characters in an RFC is for them to be wrapped in a `<contact>` element in the XML.  Unfortunately, that can't be triggered from MD right now.  One this is approved, the RFC editor can massage the XML to add the required wrapping.  This was done in RFC 9147 ([md](https://github.com/tlswg/dtls13-spec/blob/master/draft-ietf-tls-dtls13.md?plain=1#L2732), [xml](https://www.rfc-editor.org/rfc/rfc9147.xml), [html](https://www.rfc-editor.org/rfc/rfc9147.html), search for "Vyncke").

Flagging this for handling in AUTH48, which is the step in the process where we work with the RFC editor on things like this.

**Comment by seanturner** [comment]
Thanks for flagging this for AUTH48. There is zero chance I would have remember this.

**Comment by cabo** [comment]
What's wrong with the current kramdown-rfc support?  Please open an issue at rfc.space!

**Comment by cabo** [comment]
mnot wrote this up for your convenience...

https://github.com/cabo/kramdown-rfc/wiki/Syntax2#authors-contributors
