### ISSUE TITLE
Does sender_index start at zero or one?

### ISSUE THREAD

**Issue by rohan-wire** [mlswg/mls-protocol#732]
The `sender_index` is used to specify which signature key/Credential in the `external_senders` extension signed an external proposal. Nothing in the protocol specification says if the index starts from zero or from one. The `leaf_index` starts from one. I suggest we specify that the `sender_index` also starts at *one*.

**Comment by raphaelrobert** [comment]
Section 5.1.1. states

> Each leaf node in a ratchet tree is given an index (or leaf index), starting at 0 from the left to 2^d - 1 at the right (for a tree with 2^d leaves). A tree with 2^d leaves has 2^(d+1) - 1 nodes, including parent nodes.

`sender_index` is conceptually a leaf index, so it should also start at 0.

**Comment by rohan-wire** [comment]
Thanks. Yes you are right, the other indexes start at zero, so this one should as well. I will write a very short PR to make it clear.
