### ISSUE TITLE
Include last updated epoch in leaf nodes?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#748]
Inspired by #731 -- it seems like when someone issues an Update or Commit, they know the epoch in which it will be committed, and could include that under the signature for their LeafNode.  Especially in the Commit case, this could improve validation of parent hashes, since the leaf node to which a parent node chains via the parent hash should be the leaf node in that parent node's subtree that most recently updated.  A PR would have roughly the following form:

* Update LeafNode to include the following (plus corresponding updates to `LeafNodeTBS`):

```diff
     LeafNodeSource leaf_node_source;
     select (LeafNode.leaf_node_source) {
         case key_package:
             Lifetime lifetime;
 
         case update:
-            struct{};
+            uint64 update_epoch;
 
         case commit:
+            uint64 commit_epoch;
             opaque parent_hash<V>;
     }
```

* In `{{leaf-node-validation}}`, add the following checks:
    * When verifying a Update or Commit message, check that `update_epoch` / `commit_epoch` is the current epoch
    * When verifying a tree, check that for all leaves, `update_epoch` / `commit_epoch` is before the current epoch if present

(Note that we cannot just add it on the signature side, as with #731, since a new joiner won't know the right values.)

The main arguments that come to mind against making this change are: (1) The above rational isn't super strong, in that it's just a check on the ordering that the parent hash already provides.  (2) This could be cleanly done in a LeafNode extension.

**Comment by bifurcation** [comment]
cc @TWal @mulmarta @kkohbrok

**Comment by uhoreg** [comment]
FWIW, this could create a problem with my proposed (experimental) [decentralised MLS work](https://gitlab.matrix.org/matrix-org/mls-ts/-/blob/decentralised2/decentralised.org) because whenever we refer to an epoch, we also need to record the member who created the epoch.  It wouldn't be a dealbreaker, though, since we could always stick that information in an extension.

**Comment by bifurcation** [comment]
Just to be confirm I understand @uhoreg -- it seems like this would capture *part* of the information you need for DMLS, but not all of it (you would still need the committer).  So it's not so much a conflict as just insufficient to solve the problem.

**Comment by uhoreg** [comment]
Yes, that's correct.

**Comment by kkohbrok** [comment]
I like this change, as it further tightens the bound between the ratchet tree and the rest of the group state.

**Comment by bifurcation** [comment]
Interesting idea @TWal.  Just to confirm I understand, the algorithm for recovering unmerged leaves would be something like:

```
def unmerged_leaves(P):
  most_recent_commit_epoch = max({ L.committed_epoch : L \in leaves(P) })
  # Note: It MUST be the case that P is parent-hash chained to the leaf from which this max comes
  return { L \in P.leaves : L.added_epoch > most_recent_commit_epoch }
```

That's a pretty non-trivial algorithm to implement (unless maybe it were integrated with parent-hash validation on a tree), on top of the structure complexity to add the signed field.

So I agree that seems like a big change at this point.  But the change in this PR seems like a good compromise.

**Comment by uhoreg** [comment]
> FWIW, this could create a problem with my proposed (experimental) [decentralised MLS work](https://gitlab.matrix.org/matrix-org/mls-ts/-/blob/decentralised2/decentralised.org) because whenever we refer to an epoch, we also need to record the member who created the epoch. It wouldn't be a dealbreaker, though, since we could always stick that information in an extension.

Actually, looking at this again, we don't need any extra information to record the member who created the epoch, because by definition, the creator of the epoch that modified the leaf node is the owner of the leaf node.

And, in fact, in decentralised MLS, we add a "generation" counter to each leaf node to enable picking the most recent key package in the event multiple trees need to be merged together and have different key packages for some leaves.  This field could be used instead of the "generation" extension.

**Comment by bifurcation** [comment]
There was agreement on the 2022-12-08 interim to not fix this issue.  It can be done in an extension.
