### ISSUE TITLE
allow sending a different Welcome message to each user

### ISSUE THREAD

**Issue by uhoreg** [mlswg/mls-protocol#753]
From my reading, it looks like the creator of an epoch must send the exact same `Welcome` message to each new user.  However, in some systems, it is more efficient to send a different message to each user, only containing the `EncryptedGroupSecrets` intended for them, rather than the `EncryptedGroupSecrets` for all new members.  As far as I can tell, no changes are required on the recipient side.

I'm running some performance testing, trying to add thousands of members at a time, and the `Welcome` messages are hundreds of kilobytes large.  In a federated environment, this could be copied to multiple servers, with the vast majority of that being unnecessary data.

**Comment by bifurcation** [comment]
Good point @uhoreg. I filed #754.  In the case, you would do something like send a Welcome per home server?

**Comment by uhoreg** [comment]
Thanks.

With the way that Matrix currently works, it would probably be best to send a separate message per user, since the current endpoint for sending messages directly to devices requires specifying the message separately for each recipient, and implementations (AFAIK) currently don't do deduplication.  In the future, it might be possible to do it differently.
