### ISSUE TITLE
Interaction of MLS and application

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#762]
_Comment by @paulwouters_

I find the interaction with the application layer not clear. Not much is mentioned in this document. How can a group have an administrator? How is that enforced at the MLS layer? How do ACLs interact with MLS? (How are DoS attacks mitigated (eg spam attempts to join any group). What hooks would be in the authentication service and/or delivery server? How would clients know the properties of these two services?

This includes how it is not clear to me how race conditions are handled. What if two members try to expel each other at the same time? What if the group is so large, members always get their epoch wrong for things like Commit messages?

**Comment by rohan-wire** [comment]
While instant messaging was one of the big motivators for MLS, it is not the only one to be implemented in the same timeframe. 

In MIMI for example we are planning to have a whole work item that specifies many more constraints on how the DS would be expected to work in an *instant messaging* context. Whereas we have implementors of MLS who are planning to do things very differently for an IoT communication application.

**Comment by paulwouters** [comment]
I'll reread the architecture bit again about the DS, but it still feels to me it could be made more clear.
