### ISSUE TITLE
memberlist unavailble before joining

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#779]
_Comment by @paulwouters_

~~~ 
   When a client A wants to establish a group with B and C, it first
   initializes a group state containing only itself and downloads
   KeyPackages for B and C.  For each member, A generates an Add and
   Commit message adding that member, and broadcasts them to the group.
~~~
So if A joins before B, A cannot tell B will become a group member ? eg the fact that A invited B and C is not visible to C or B and might come as a surprise.

**Comment by rohan-wire** [comment]
Also, at the application layer, if you wanted to publish (for example) a moderation policy or a "list of authorized domains" policy, or a credential policy and a set of trusted root certificates for validating members of the group, you could do that in a GroupContextExtension so everyone in the group could see it and agree that it was the same. Leaving this out of the base protocol, but having the tools to do this is one of my favorite features of MLS.

**Comment by paulwouters** [comment]
fine with me. thanks
