### ISSUE TITLE
Prospective member or member ?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#780]
_Comment by @paulwouters_

~~~ 
   It also generates a Welcome message and sends this directly to the
  new member
~~~
Should this be "prospective member" or "invitee" ? They haven't joined yet, have they?

**Comment by bifurcation** [comment]
From the perspective of the group, they are joined.  Once the Commit adding the new member is processed and the new epoch starts, that member is able to access the group's secrets.  The only thing "provisional" about the membership is that the new member hasn't initialized their local state.  We use "new member" consistently to mean the subject of an Add proposal, and I don't think this is a big enough distinction to merit more terminology.

**Comment by rohan-wire** [comment]
Another way to look at it is that keying information from the new member is already incorporated into the group, therefore they are a member and not a provisional member.

**Comment by paulwouters** [comment]
Ah yes. Perhaps a single line explaining this at the quoted location could be useful, but is not required
