### ISSUE TITLE
Can?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#796]
_Comment by @paulwouters_

~~~ 
   The set of members
   involved in the group can change from one epoch to the next
~~~
Isn't it the definition of epoch that there is a change in members? Paul: i think members refreshing their keys also means a new epoch?

**Comment by bifurcation** [comment]
Right, if there are no Add or Remove proposals, then the membership does not change.   So you could have say Update or PSK proposals, or no proposals at all (just refresh the committer's leaf).

Propose closing with no action.

**Comment by paulwouters** [comment]
thanks. yes you can close this one
