### ISSUE TITLE
Discuss metadata privacy

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#813]
_Comment by @paulwouters_

That is quite some information that must be publicly available to allow external Add requests. This leaks information, eg same epoch means the group membership did not change, etc etc. I hope this will appear in the Security Considerations later :)

**Comment by bifurcation** [comment]
I suppose between this and #779, we should add a subsection to the Security Considerations on metadata privacy.

**Comment by Bren2010** [comment]
I'm not sure #823 actually resolves this?

**Comment by bifurcation** [comment]
Oops, that's correct @Bren2010.  Had it in my notes among the others.
