### ISSUE TITLE
Citations to security analysis

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#815]
_Comment by @paulwouters_

~~~ 
though a complete security analysis is outside of the scope of this document.
~~~
Hmmm :P

**Comment by bifurcation** [comment]
Cf. RFC 8446

> Appendix E. Overview of Security Properties
> 
>   A complete security analysis of TLS is outside the scope of this document.

We could provide some more citations to the analyses that are now in the literature if you think that would help.

**Comment by bifurcation** [comment]
CC @psyoptix @TWal @mulmarta for citations

**Comment by rohan-wire** [comment]
> Cf. RFC 8446
> 
> > Appendix E. Overview of Security Properties
> > A complete security analysis of TLS is outside the scope of this document.
> 
> We could provide some more citations to the analyses that are now in the literature if you think that would help.

They are also in this architecture document PR:
https://github.com/mlswg/mls-architecture/pull/119/files

**Comment by bifurcation** [comment]
Oh good, I'll just add a citation over to mls-architecture.
