### ISSUE TITLE
"Pre-warm" trees with some double-joined nodes

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#88]
In the current draft, creating a group is done with `n` Add messages, which just place the members of the group at the leaves of the tree.  This means that newly-created trees have some "warm up" time during which early operations are roughly linear size, gradually converging to log size.

This state of affairs is unavoidable if we are not going to have double joins.  However, it might be tolerable to have double joins, so long as (1) they only happen at group creation time and (2) they resolve relatively quickly.

For example, you might create a special `Init` message, distinct from Add, which initializes a tree with the members at the leaves, but also some intermediate nodes filled in by the creator (and thus double-joined).  These nodes would be overwritten as members update, but the double-joins would only be fully resolved once all members update (or `1/2^{k}` of the members if `k` lower layers are not double-joined).

**Comment by seanturner** [comment]
Closing until deployment shows we need this.
