### ISSUE TITLE
Figure 14: "Derivation of ratchet tree keys along a direct path" don't correspond to the prose

### ISSUE THREAD

**Issue by TWal** [mlswg/mls-protocol#880]
In the diagram, it looks like `path_secret[0]` and the leaf node's public/private keys are generated from `leaf_secret`.
However this is not what the prose says: "`path_secret[0]` is sampled at random" and "Generate a fresh HPKE key pair for the leaf".

Looks like it's an artifact from past versions of MLS?

**Comment by bifurcation** [comment]
Fixed in #883
