### ISSUE TITLE
User-Initiated Add

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#91]
Currently, in order for a new member to join a group, an existing member needs to add them to the group.  Certain use cases work more naturally if a new joiner can initiate the add process.  I think that broadly speaking we want a process here where someone outside the group can (1) request to be added and (2) send to the group, but cannot receive from the group until added.

Some things to consider here:

* Anything that is revealed to a joiner that joins this way is effectively public.  Should they be able to see, e.g., the roster?

* How should these interactions relate to the key schedule?  Assuming there's some `AddRequest` message, should it be included into the transcript at Add time?

* What happens if there are multiple parallel requests?

**Comment by bifurcation** [comment]
At the 2019-01 interim, we discussed a "reversed Add" flow, where:

* Group publishes an InitKey
* The new joiner sends a UIK to the group and establishes a shared secret with the group
* This initiates a period where the new joiner can send, but nobody in the group can
* Before anyone in the group can send, they have to send a Welcome for the new joiner
* ... which initiates an epoch where they are fully joined

**Comment by ipmipest** [comment]
In certain use cases, such as enterprise messaging there may/could/might be a problem if "**Any** member of the group can download an ClientInitKey for a new client and broadcast an Add message". An enterprise may wish to enforce access restrictions for certain information such as ClientInitKey. Just thinking about security related issues that may be most easily noticed by corp IT types.

On the other hand this may be best dealt with outside the protocol scope.

**Comment by beurdouche** [comment]
@bifurcation I think this is fixed by #240 correct? A user can propose to Add herself.

**Comment by bifurcation** [comment]
Partly addressed by #240.  To complete the story, we need a "send-to-group-from-outside" mechanism.  Leaving this open until we have that.

**Comment by Bren2010** [comment]
I don't think a "send-to-group-from-outside" mechanism will be possible, given that we try quite hard to prevent any key material from inside the group from ever being published.
