### ISSUE TITLE
ACK / NACK

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#92]
In early discussions around MLS, people expressed interest in specifying how to do ACKs / NACKs on messages.  Questions to address:

* How are ACKs / NACKs encoded?
* How are they cryptographically protected? (signed, encrypted, MAC'ed, etc.)
* When should they be sent?
* Do they apply to handshake messages?  application messages?  both?

**Comment by beurdouche** [comment]
We should discuss that today

**Comment by bifurcation** [comment]
This was discussed at the January 2020 interim.  The conclusion there was that error recovery is a sufficiently complex topic that it merits a separate specification, which may extend the protocol, e.g., to add an Ack message or a Resync proposal.
