### ISSUE TITLE
Clarify uniqueness constraints on UIK IDs

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#96]
Consumers should not assume that UIK IDs are unique across users.

**Comment by beurdouche** [comment]
The current text says:
```UserInitKeys also contain an identifier chosen by the client, which the client
MUST assure uniquely identifies a given UserInitKey object among the
set of UserInitKeys created by this client.```

Would it be realistic to say that the Delivery Service MUST check when accepting a key that the UIK identifier is not used by another key ? @bifurcation @raphaelrobert

**Comment by raphaelrobert** [comment]
I'd be fine with that requirement for the DS.

**Comment by bifurcation** [comment]
Given that arch PR and the fact that the doc already says "the client MUST assure uniquely identifies a given UserInitKey object among the set of UserInitKeys created by this client", I think we can call this fixed.
